[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Ortalab Compat
[[patches]] # Pack spawn fix
[patches.pattern]
target = '''=[SMODS ortalab "objects/stakes.lua"]'''
pattern = '''
if v.in_pool and type(v.in_pool) == 'function' then 
	local res, pool_opts = v:in_pool()
	pool_opts = pool_opts or {}
	add = res and (add or pool_opts.override_base_checks)
end
'''
position = 'at'
payload = '''
local res, pool_opts = SMODS.add_to_pool(v)
pool_opts = pool_opts or {}
add = res and (add or pool_opts.override_base_checks)
'''
match_indent = true
times = 1

[[patches]] # Small and Big Blind pool manipulation
[patches.pattern]
target = '''=[SMODS ortalab "util/functions.lua"]'''
pattern = '''
for k, v in pairs(G.GAME.banned_keys) do
    if eligible_bosses[k] then eligible_bosses[k] = nil end
end
'''
position = 'after'
payload = '''
for k, v in pairs(eligible_bosses) do
    if G.P_BLINDS[k] and not SuperRogue.is_object_mod_active(G.P_BLINDS[k]) then eligible_bosses[k] = nil end
end
'''
match_indent = true
times = 2

[[patches]] # Mythos shop slot compat
[patches.pattern]
target = 'game.lua'
pattern = '''
elseif G.GAME.ortalab.vouchers.mythos_shop_slot then
'''
position = 'at'
payload = '''
elseif G.GAME.ortalab.vouchers.mythos_shop_slot and G.GAME.sr_active_mod_pool['ortalab'] then
'''
match_indent = true
times = 1

# Prism Compat
[[patches]] # Pass ante_end into hook
[patches.pattern]
target = '''=[SMODS Prism "objects/stakes.lua"'''
pattern = '''
function ease_ante(mod)
'''
position = 'at'
payload = '''
function ease_ante(mod, ante_end)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS Prism "objects/stakes.lua"'''
pattern = '''
function ease_ante(mod)
'''
position = 'at'
payload = '''
orig_ease_ante(mod, ante_end)
'''
match_indent = true
times = 1

# Cryptid Compat
[[patches]] # Accomodate pool rates totalling for Cryptid patches
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
total_rate = total_rate + ( G.GAME[v:lower()..'_rate'] * (G.GAME.cry_percrate[v:lower()]/100) )
'''
position = 'at'
payload = '''
if SuperRogue.is_pool_available(v) then
    total_rate = total_rate + ( G.GAME[v:lower()..'_rate'] * (G.GAME.cry_percrate[v:lower()]/100) )
end
'''
match_indent = true
times = 1

[[patches]] # Accomodate pool rates table inserting for Cryptid patches
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] * ((num or 100) / 100) })
'''
position = 'at'
payload = '''
if SuperRogue.is_pool_available(v) then
    table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] * ((num or 100) / 100) })
end
'''
match_indent = true
times = 1