[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add Mods tab to run info tabs
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
{
    label = localize('b_vouchers'),
    tab_definition_function = G.UIDEF.used_vouchers,
},
'''
position = 'after'
payload = '''
{
    label = localize('b_sr_mods'),
    tab_definition_function = G.UIDEF.sr_activated_mods,
},
'''
match_indent = true
times = 1

# Prevent Debuff loc_vars override
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
elseif self.debuff then
'''
position = 'at'
payload = '''
elseif self.debuff and self.config.center_key ~= 'c_sr_mod_cons' then
'''
match_indent = true
times = 1
