[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Special collection base score display for The Point
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{n=G.UIT.T, config={text = blind.mult..localize('k_x_base'), scale = 0.4, colour = G.C.RED}},"
position = "at"
payload = "{n=G.UIT.T, config={text = blind.key == 'bl_pencil_caret' and '^'..blind.mult..' Base' or blind.mult..localize('k_x_base'), scale = 0.4, colour = G.C.RED}},"
match_indent = true

# Update Parchment Glove when hand is played
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.hands_played = G.GAME.hands_played + 1"
position = "after"
payload = 'StrangeLib.dynablind.update_blind_scores(StrangeLib.dynablind.find_blind("bl_pencil_glove"))'
match_indent = true
