[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Hod
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = specific_vars or {}}"
position = "after"
payload = """
if G.GAME.hod_deck and G.jokers and G.jokers.cards then
    for i, v in ipairs(G.jokers.cards) do
        if G.jokers.cards[i] == card then
            info_queue[#info_queue+1] = {set = 'Other', key = 'hod_training', vars = card.ability.hod_training or {0}}
        end
    end
end
"""
match_indent = true


# Hokma
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)"
position = "at"
payload = """if G.GAME.selected_back.name ~= "b_ruina_hokma" then
    G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)
end
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)"
position = "at"
payload = """if G.GAME.selected_back.name ~= "b_ruina_hokma" then
    G.GAME.current_round.discards_left = math.max(0, G.GAME.round_resets.discards + G.GAME.round_bonus.discards)
end
"""
match_indent = true
