[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Needed for SMODS compat
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = 'init_localization()'
position = "before"
payload = '''
if not (SMODS and SMODS.can_load) then FlowerPot.load_localization() end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'engine/controller.lua'
pattern = "function Controller:key_press_update(key, dt)"
position = "after"
payload = '''
    if key == "escape" and G.ACTIVE_FLOWPOT_UI then
        if G.ACTIVE_FLOWPOT_UI then
            G.FUNCS.exit_mods()
        end
        FlowerPot.GLOBAL.IN_DECK_STATS = nil
        FlowerPot.GLOBAL.LAST_DECK_STAT_PAGE = nil
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = 'function desc_from_rows(desc_nodes, empty, maxw)'
position = "after"
payload = '''
if FlowerPot.GLOBAL.IN_DECK_STATS and empty then
    empty = nil
end
'''
match_indent = true