name: Manual Zip and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release title'
        required: true
        default: 'Goonlatro'

jobs:
  release:
    name: Create GitHub Release with ZIP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip repository
        run: |
          zip -r Goonlatro.zip . -x "*.git*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.release_name || github.event.inputs.tag }}
          files: Goonlatro.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
