[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Ramen' and not context.blueprint then"
position = "at"
payload = "if self.ability.name == 'Ramen' and not context.blueprint and SMODS.food_expires(context) then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Popcorn' and not context.blueprint then"
position = "at"
payload = "if self.ability.name == 'Popcorn' and not context.blueprint and SMODS.food_expires(context) then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Ice Cream' and not context.blueprint then"
position = "at"
payload = "if self.ability.name == 'Ice Cream' and not context.blueprint and SMODS.food_expires(context) then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Seltzer' and not context.blueprint then"
position = "at"
payload = "if self.ability.name == 'Seltzer' and not context.blueprint and SMODS.food_expires(context) then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Turtle Bean' and not context.blueprint then"
position = "at"
payload = "if self.ability.name == 'Turtle Bean' and not context.blueprint and SMODS.food_expires(context) then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Gros Michel' or self.ability.name == 'Cavendish' then"
position = "at"
payload = "if (self.ability.name == 'Gros Michel' or self.ability.name == 'Cavendish') and SMODS.food_expires(context) then"
match_indent = true