[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

[[patches]]
[patches.pattern]
target = '''=[SMODS Neato_Jokers "cards/bananastand.lua"]'''
pattern = "if pseudorandom('stand') < G.GAME.probabilities.normal/card.ability.extra.destroy_chance then"
position = "at"
payload = "if SMODS.food_expires() and pseudorandom('stand') < G.GAME.probabilities.normal/card.ability.extra.destroy_chance then"
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Neato_Jokers "cards/icecreamsandwhich.lua"]'''
pattern = "elseif context.end_of_round and not context.repetition and not context.game_over and not context.blueprint and not context.individual then"
position = "at"
payload = "elseif context.end_of_round and not context.repetition and not context.game_over and not context.blueprint and not context.individual and SMODS.food_expires() then"
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS Neato_Jokers "cards/frostedprimerib.lua"]'''
pattern = "elseif context.after and not context.blueprint then"
position = "at"
payload = "elseif context.after and not context.blueprint and SMODS.food_expires() then"
match_indent = true