[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
    for k, v in ipairs(G.play.cards) do
        if (not v.shattered) and (not v.destroyed) then
            draw_card(G.play,G.discard, it*100/play_count,'down', false, v)
            it = it + 1
        end
    end
'''
position = "at"
payload = '''
    local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)
    local context = { scoring_name = text, scoring_hand = scoring_hand, full_hand = G.play.cards }
    for k, v in ipairs(G.play.cards) do
        if (not v.shattered) and (not v.destroyed) then
            draw_card(G.play, SMODS.return_to_hand(v, context) and G.hand or G.discard, it*100/play_count,'down', false, v)
            it = it + 1
        end
    end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then"
position = "before"
payload = '''
if _append == "jud" and v.key == 'j_csau_hell' then
    add = false
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))'''
position = "at"
payload = '''
local voucher_discount = 0
if self.ability.set == "Voucher" then
    voucher_discount = G.GAME.voucher_discount or 0
end
self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*((100 - G.GAME.discount_percent)/100)*((100 - voucher_discount)/100)))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "play_sound('tarot2', 0.76, 0.4);return true end}))"
position = "at"
payload = "play_sound(G.FUNCS.nutbuster_active() and 'csau_doot' or 'tarot2', G.FUNCS.nutbuster_active() and 1 or 0.76, 0.4);return true end}))"
match_indent = true
times = 1
