[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if G.shop then
    G.shop.alignment.offset.y = G.shop.alignment.offset.py
    G.shop.alignment.offset.py = nil
end'''
position = "after"
payload = '''if G.morshu_save then
    G.morshu_save.alignment.offset.y = G.morshu_save.alignment.offset.py
    G.morshu_save.alignment.offset.py = nil
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if G.shop and not G.shop.alignment.offset.py then
  G.shop.alignment.offset.py = G.shop.alignment.offset.y
  G.shop.alignment.offset.y = G.ROOM.T.y + 29
end'''
position = "after"
payload = '''if G.morshu_save and not G.morshu_save.alignment.offset.py then
  G.morshu_save.alignment.offset.py = G.morshu_save.alignment.offset.y
  G.morshu_save.alignment.offset.y = G.ROOM.T.y + 29
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if G.shop and G.shop.alignment.offset.py then
    G.shop.alignment.offset.y = G.shop.alignment.offset.py
    G.shop.alignment.offset.py = nil
end'''
position = "after"
payload = '''if G.morshu_save and G.morshu_save.alignment.offset.py then
    G.morshu_save.alignment.offset.y = G.morshu_save.alignment.offset.py
    G.morshu_save.alignment.offset.py = nil
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.shop.alignment.offset.y = G.ROOM.T.y + 29
G.SHOP_SIGN.alignment.offset.y = -15'''
position = "at"
payload = '''G.shop.alignment.offset.y = G.ROOM.T.y + 29
if G.morshu_save then G.morshu_save.alignment.offset.y = G.ROOM.T.y + 29 end
G.SHOP_SIGN.alignment.offset.y = -15'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.load_shop_vouchers = nil'''
position = "after"
payload = '''self.load_morshu_area = nil
if G.morshu_save then G.morshu_save:remove() end
G.morshu_save = nil'''
match_indent = true
times = 1